"""create

Revision ID: 3a2863f4b6be
Revises: 
Create Date: 2026-05-07 09:06:11.410515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2863f4b6be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('trainer_name', sa.String(length=255), nullable=False),
    sa.Column('rule', sa.String(length=6), nullable=False),
    sa.Column('season', sa.String(length=255), nullable=True),
    sa.Column('regulation', sa.String(length=255), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_created_at'), 'articles', ['created_at'], unique=False)
    op.create_index(op.f('ix_articles_rank'), 'articles', ['rank'], unique=False)
    op.create_index(op.f('ix_articles_rate'), 'articles', ['rate'], unique=False)
    op.create_index(op.f('ix_articles_regulation'), 'articles', ['regulation'], unique=False)
    op.create_index(op.f('ix_articles_rule'), 'articles', ['rule'], unique=False)
    op.create_index(op.f('ix_articles_season'), 'articles', ['season'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('natures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pokemons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('regulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sort_order')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sort_order')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_category', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('article_pokemons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('tera_type_id', sa.Integer(), nullable=True),
    sa.Column('ability_id', sa.Integer(), nullable=True),
    sa.Column('nature_id', sa.Integer(), nullable=True),
    sa.Column('ev_h', sa.Integer(), nullable=True),
    sa.Column('ev_a', sa.Integer(), nullable=True),
    sa.Column('ev_b', sa.Integer(), nullable=True),
    sa.Column('ev_c', sa.Integer(), nullable=True),
    sa.Column('ev_d', sa.Integer(), nullable=True),
    sa.Column('ev_s', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['nature_id'], ['natures.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemons.id'], ),
    sa.ForeignKeyConstraint(['tera_type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_pokemons_ability_id'), 'article_pokemons', ['ability_id'], unique=False)
    op.create_index(op.f('ix_article_pokemons_article_id'), 'article_pokemons', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_pokemons_ev_a'), 'article_pokemons', ['ev_a'], unique=False)
    op.create_index(op.f('ix_article_pokemons_ev_b'), 'article_pokemons', ['ev_b'], unique=False)
    op.create_index(op.f('ix_article_pokemons_ev_c'), 'article_pokemons', ['ev_c'], unique=False)
    op.create_index(op.f('ix_article_pokemons_ev_d'), 'article_pokemons', ['ev_d'], unique=False)
    op.create_index(op.f('ix_article_pokemons_ev_h'), 'article_pokemons', ['ev_h'], unique=False)
    op.create_index(op.f('ix_article_pokemons_ev_s'), 'article_pokemons', ['ev_s'], unique=False)
    op.create_index(op.f('ix_article_pokemons_item_id'), 'article_pokemons', ['item_id'], unique=False)
    op.create_index(op.f('ix_article_pokemons_nature_id'), 'article_pokemons', ['nature_id'], unique=False)
    op.create_index(op.f('ix_article_pokemons_pokemon_id'), 'article_pokemons', ['pokemon_id'], unique=False)
    op.create_index(op.f('ix_article_pokemons_tera_type_id'), 'article_pokemons', ['tera_type_id'], unique=False)
    op.create_table('article_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_tags_article_id'), 'article_tags', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_tags_tag_id'), 'article_tags', ['tag_id'], unique=False)
    op.create_table('article_pokemon_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_pokemon_id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_pokemon_id'], ['article_pokemons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_pokemon_moves_article_pokemon_id'), 'article_pokemon_moves', ['article_pokemon_id'], unique=False)
    op.create_index(op.f('ix_article_pokemon_moves_move_id'), 'article_pokemon_moves', ['move_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_pokemon_moves_move_id'), table_name='article_pokemon_moves')
    op.drop_index(op.f('ix_article_pokemon_moves_article_pokemon_id'), table_name='article_pokemon_moves')
    op.drop_table('article_pokemon_moves')
    op.drop_index(op.f('ix_article_tags_tag_id'), table_name='article_tags')
    op.drop_index(op.f('ix_article_tags_article_id'), table_name='article_tags')
    op.drop_table('article_tags')
    op.drop_index(op.f('ix_article_pokemons_tera_type_id'), table_name='article_pokemons')
    op.drop_index(op.f('ix_article_pokemons_pokemon_id'), table_name='article_pokemons')
    op.drop_index(op.f('ix_article_pokemons_nature_id'), table_name='article_pokemons')
    op.drop_index(op.f('ix_article_pokemons_item_id'), table_name='article_pokemons')
    op.drop_index(op.f('ix_article_pokemons_ev_s'), table_name='article_pokemons')
    op.drop_index(op.f('ix_article_pokemons_ev_h'), table_name='article_pokemons')
    op.drop_index(op.f('ix_article_pokemons_ev_d'), table_name='article_pokemons')
    op.drop_index(op.f('ix_article_pokemons_ev_c'), table_name='article_pokemons')
    op.drop_index(op.f('ix_article_pokemons_ev_b'), table_name='article_pokemons')
    op.drop_index(op.f('ix_article_pokemons_ev_a'), table_name='article_pokemons')
    op.drop_index(op.f('ix_article_pokemons_article_id'), table_name='article_pokemons')
    op.drop_index(op.f('ix_article_pokemons_ability_id'), table_name='article_pokemons')
    op.drop_table('article_pokemons')
    op.drop_table('types')
    op.drop_table('trends')
    op.drop_table('tags')
    op.drop_table('seasons')
    op.drop_table('regulations')
    op.drop_table('pokemons')
    op.drop_table('natures')
    op.drop_table('moves')
    op.drop_table('items')
    op.drop_index(op.f('ix_articles_season'), table_name='articles')
    op.drop_index(op.f('ix_articles_rule'), table_name='articles')
    op.drop_index(op.f('ix_articles_regulation'), table_name='articles')
    op.drop_index(op.f('ix_articles_rate'), table_name='articles')
    op.drop_index(op.f('ix_articles_rank'), table_name='articles')
    op.drop_index(op.f('ix_articles_created_at'), table_name='articles')
    op.drop_table('articles')
    op.drop_table('abilities')
    # ### end Alembic commands ###
